const {chromium}=require('/Users/kevinsyuan/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const fs=require('fs');const assert=require('assert');
(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});let errors=[];p.on('pageerror',e=>errors.push(e.message));const states=[];const capture=fs.readFileSync('evidence/capture.js','utf8');
await p.goto('http://localhost:4180');await p.evaluate(()=>document.fonts.ready);
await p.locator('.header-search').click();await p.getByRole('textbox',{name:'搜索关键词'}).fill('BM25');await p.locator('.result').first().waitFor();assert(await p.locator('.result').count()>0);await p.getByRole('textbox',{name:'搜索关键词'}).fill('zzzxnonexistent');assert(await p.getByText('没有找到相关内容').isVisible());await p.getByRole('button',{name:'清空搜索'}).click();assert.equal(await p.getByRole('textbox',{name:'搜索关键词'}).inputValue(),'');await p.keyboard.press('Escape');assert.equal(await p.getByRole('dialog').count(),0);
await p.getByRole('button',{name:'收藏：企业检索基础',exact:true}).click();await p.locator('.chapter-filters').getByRole('radio',{name:'收藏',exact:true}).click();assert.equal(await p.locator('.chapter-row').count(),1);await p.reload();assert.equal(await p.getByRole('button',{name:'取消收藏：企业检索基础',exact:true}).count(),1);await p.getByRole('button',{name:'取消收藏：企业检索基础',exact:true}).click();
await p.getByRole('button',{name:'Switch to English'}).click();assert(await p.getByText('Connect the concepts.').isVisible());await p.getByRole('button',{name:'切换为中文'}).click();
for(const width of [390,1440,1728]){await p.setViewportSize({width,height:width===390?844:1000});await p.goto('http://localhost:4180/#home');await p.evaluate(()=>document.fonts.ready);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);states.push(await p.evaluate(capture));await p.screenshot({path:`evidence/home-${width}.png`});await p.goto('http://localhost:4180/#read');assert(await p.getByRole('heading',{name:'企业检索基础',exact:true}).isVisible());assert.equal(await p.locator('.chapter-body tbody tr').count(),5);assert.equal(await p.locator('#comparison').count(),1);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth),width);states.push({...await p.evaluate(capture),name:`reader-${width}`});await p.screenshot({path:`evidence/reader-${width}.png`});}
await p.getByRole('button',{name:'切换深色模式'}).click();await p.screenshot({path:'evidence/reader-dark.png'});await p.goto('http://localhost:4180/#home');await p.screenshot({path:'evidence/home-dark.png'});await p.getByRole('button',{name:'切换浅色模式'}).click();
await p.setViewportSize({width:390,height:844});await p.getByRole('button',{name:'打开章节导航'}).click();assert(await p.getByRole('dialog').isVisible());states.push({...await p.evaluate(capture),name:'mobile-menu-open'});await p.keyboard.press('Escape');assert.equal(await p.getByRole('dialog').count(),0);
await p.locator('.header-search').click();await p.getByRole('textbox',{name:'搜索关键词'}).fill('BM25');states.push({...await p.evaluate(capture),name:'mobile-search-open'});await p.screenshot({path:'evidence/search-390.png'});await p.keyboard.press('Escape');
assert.deepEqual(errors,[]);fs.writeFileSync('evidence/spacing.json',JSON.stringify(states));fs.writeFileSync('evidence/qa.json',JSON.stringify({passed:true,checks:['search results','no results','clear search','escape closes and does not reopen','bookmark filter','bookmark persistence','locale toggle','chapter table content','390/1440/1728 no viewport overflow','dark theme','mobile menu','runtime errors'],errors},null,2));console.log('PASS: 12 interaction/layout checks; saved 8 rendered spacing states.');await b.close()})().catch(e=>{console.error(e);process.exit(1)});
