const {chromium}=require('playwright');const fs=require('fs');const path=require('path');
const out='/Users/kevinsyuan/.gstack/projects/ai-engineer-handbook/designs/full-visual-audit-20261002';fs.mkdirSync(out,{recursive:true});
const capture=fs.readFileSync(path.join(out,'capture.js'),'utf8');const chapters=require('../src/chapters.json');const routes=[{slug:'home',url:'#home'},{slug:'map',url:'#map'},...chapters.map(c=>({slug:c.slug,url:'#read/'+c.slug}))];
(async()=>{const b=await chromium.launch();const results=[],errors=[],spacing=[];
for(const dark of [false,true])for(const en of [false,true]){const context=await b.newContext({reducedMotion:'reduce'});await context.addInitScript(({dark,en})=>{localStorage.setItem('preview-theme',JSON.stringify(dark));localStorage.setItem('preview-locale',JSON.stringify(en));window.__name=(fn)=>fn;},{dark,en});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));
for(const width of [375,390,768,1024,1440,1728]){await p.setViewportSize({width,height:width<768?844:1000});for(const route of routes){await p.goto('http://localhost:4180/'+route.url);await p.locator('main').waitFor();if(route.url.startsWith('#read'))await p.locator('.canonical-content').waitFor();await p.evaluate(()=>document.fonts.ready);
const metric=await p.evaluate(()=>{const main=document.querySelector('main');const clipped=[],outside=[];for(const el of main.querySelectorAll('*')){const s=getComputedStyle(el),r=el.getBoundingClientRect();if(!r.width||!r.height||s.display==='none')continue;const ident=el.id||el.className||el.tagName;
if(['hidden','clip'].includes(s.overflowY)&&el.scrollHeight>el.clientHeight+3&&el.clientHeight>0)clipped.push({id:ident,text:el.textContent.slice(0,60),axis:'y',excess:el.scrollHeight-el.clientHeight});
if(r.left < -2 || r.right > innerWidth+2){let parent=el.parentElement,intentional=false;while(parent&&parent!==main){const style=getComputedStyle(parent);if(['auto','scroll'].includes(style.overflowX)){intentional=true;break;}parent=parent.parentElement;}if(!intentional&&outside.length<12)outside.push({id:ident,left:r.left,right:r.right});}}
const canon=document.querySelector('.canonical-content');return{mainOverflow:main.scrollWidth>main.clientWidth+3,workspaceOverflow:document.querySelector('.workspace').scrollWidth>document.querySelector('.workspace').clientWidth+3,clipped:clipped.slice(0,12),outside,content:(()=>{if(!canon)return;const clone=canon.cloneNode(true);clone.querySelectorAll('[data-arch-title],[data-arch-desc],[data-arch-score]').forEach(el=>el.remove());return clone.textContent.replace(/\s+/g,' ').trim();})(),headingCount:main.querySelectorAll('h1,h2,h3').length};});
if(route.url.startsWith('#read')){const payload=JSON.parse(fs.readFileSync('public/content/'+route.slug+'.json'));const expected=await p.evaluate(html=>{const el=document.createElement('div');el.innerHTML=html;el.querySelectorAll('[data-arch-title],[data-arch-desc],[data-arch-score]').forEach(node=>node.remove());return el.textContent.replace(/\s+/g,' ').trim();},payload[en?'en':'zh']);metric.contentMatches=metric.content===expected;}delete metric.content;results.push({route:route.slug,width,dark,en,...metric});
if(!en&&[390,1440].includes(width)){for(const position of ['top','middle','bottom']){await p.evaluate(position=>{const el=innerWidth<=767?document.querySelector('.workspace'):document.querySelector('.chapter-body,.catalog-scroll,.knowledge-map');el.scrollTop=position==='top'?0:position==='middle'?(el.scrollHeight-el.clientHeight)/2:el.scrollHeight;},position);await p.screenshot({path:path.join(out,`${route.slug}-${width}-${dark?'dark':'light'}-${position}.jpg`),type:'jpeg',quality:65});}}
if(!en&&!dark&&[390,1440,1728].includes(width)&&['home','map',chapters[0].slug].includes(route.slug)){await p.evaluate(()=>{document.querySelector('.workspace').scrollTop=0;document.querySelector('.chapter-body,.catalog-scroll,.knowledge-map').scrollTop=0;});const state=await p.evaluate(capture);state.name=route.slug+'-'+width;spacing.push(state);}
}console.log(`Captured ${width}px ${dark?'dark':'light'} ${en?'EN':'ZH'}`);}await context.close();}
fs.writeFileSync(path.join(out,'matrix.json'),JSON.stringify({results,errors},null,2));fs.writeFileSync(path.join(out,'spacing.json'),JSON.stringify(spacing));const findings=results.filter(r=>r.mainOverflow||r.workspaceOverflow||r.outside.length||r.clipped.length||r.contentMatches===false);console.log(JSON.stringify({states:results.length,errors,findings},null,2));await b.close();})().catch(e=>{console.error(e);process.exit(1)});
