const {chromium}=require('../../node_modules/playwright');
const AxeBuilder=require('../../node_modules/@axe-core/playwright').default;
const fs=require('node:fs');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch();const results=[],states=[];try{
for(const en of [false,true])for(const dark of [false,true]){const context=await browser.newContext();await context.addInitScript(({en,dark})=>{localStorage.setItem('preview-locale',JSON.stringify(en));localStorage.setItem('preview-theme',JSON.stringify(dark));window.__name=f=>f;},{en,dark});const page=await context.newPage();
for(const width of [390,1440,1728])for(const kind of ['skills','memory']){await page.setViewportSize({width,height:1000});await page.goto('http://localhost:4181/#read/'+(kind==='skills'?'06-skills-routing':'07-memory-context-engineering'));if(kind==='skills'){await page.locator('#concept-demo').waitFor();await page.locator('#concept-demo details summary').click();}const figure=page.locator('.archify-overview');await figure.waitFor();await figure.scrollIntoViewIfNeeded();await page.evaluate(()=>document.fonts.ready);const img=figure.locator('img:visible');await img.evaluate(e=>e.decode());assert.equal(await figure.count(),1);assert.equal(await figure.evaluate(e=>e.scrollWidth>e.clientWidth+1||e.getBoundingClientRect().right>innerWidth+1),false);assert.equal(await figure.locator('a').first().getAttribute('href'),`/diagrams/${kind}-${en&&kind==='skills'?'en':'zh'}.html`);const axe=await new AxeBuilder({page}).include('.archify-overview').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(axe.violations,[]);
if(!en&&!dark&&kind==='skills'){await figure.evaluate(e=>[e,...e.querySelectorAll('*')].forEach((n,i)=>n.setAttribute('data-bd-group','archify-'+i)));const state=await page.evaluate(fs.readFileSync('/tmp/archify-spacing-capture.js','utf8'));state.elements=state.elements.filter(e=>e.groupId?.startsWith('archify-'));state.name='overview-'+width;states.push(state);await page.screenshot({path:__dirname+`/integrated-${width}.png`});}
await page.locator('.knowledge-trigger').click();assert.equal(await page.locator('.knowledge-content').isVisible(),true);results.push({en,dark,width,kind,status:'passed'});
}await context.close();}fs.writeFileSync(__dirname+'/integration.json',JSON.stringify(results,null,2));fs.writeFileSync(__dirname+'/spacing-states.json',JSON.stringify(states));console.log('Passed',results.length,'integration states');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
